apiVersion: apps/v1
kind: Deployment
metadata: 
  name: pb-portfolio
  labels: 
    app: pb-portfolio
    type: pb-services
  namespace: pb-demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pb-portfolio
  template: 
    metadata:
      labels:
        app: pb-portfolio
    spec:
      containers:
      - name: pb-portfolio
        image: sreeramsunkara/pb-portfolio-service
        ports:
        - name: http
          containerPort: 8080
        resources:
          limits:
            cpu: 0.2
            memory: "500Mi"
        env:
        - name: SPRING_DATASOURCE_USERNAME
          valueFrom:
            configMapKeyRef:
              name: db-config
              key:  db.user
        - name: SPRING_DATASOURCE_PASSWORD
          valueFrom:
            secretKeyRef:
              name: db-secret
              key: db-user-password
        - name: SPRING_DATASOURCE_URL
          valueFrom:
            configMapKeyRef:
              name: db-config
              key: db.url

---

apiVersion: v1
kind: Service
metadata:
  name: pb-portfolio
  labels:
    app: pb-portfolio
  namespace: pb-demo
spec:
  type: NodePort
  selector:
    app: pb-portfolio
  ports:
  - name: http
    port: 80
    targetPort: 8080
